In [107]:
import numpy as np
import math

In [108]:
m, n = 4, 6
A = np.array([[1, 2, 1, 0, 0, 0],
            [2, 1, 0, 1, 0, 0],
            [1, 0, 0, 0, 1, 0],
            [0, 1, 0, 0, 0, 1]])
vector_b = np.array([10, 11, 5, 4])
vector_c = np.array([20, 26, 0, 0, 0, 1])
vector_x = np.array([2, 4, 0, 3, 3, 0])
Jb = np.array([5, 2, 1, 4])




In [109]:
def basis_matrix(A, Jb, m):
    Ab = np.zeros((m, len(Jb)))
    for item in range(len(Jb)):
        Ab[: , item] = A[: , Jb[item] - 1]
    return Ab


def calculations(B, A, vector_x, i, n):   
    vector_l_col = B.dot(vector_x)
    if vector_l_col[i - 1] == 0:
        return None
    vector_l = vector_l_col.copy()
    vector_l[i - 1] = -1    
    a = ((-1) / vector_l_col[i-1]) 
    vector_L = vector_l.dot(a)
    matrix_eye = np.eye(n)
    matrix_eye[:, i - 1] = vector_L
    Q = matrix_eye.dot(B)
    return Q


In [110]:

def create_vector_x_new(vector_x, vector_z, vector_jb, j0, theta, m):
    vector_x_new = np.zeros_like(vector_x)
    for i in range(m):
        index = vector_jb[i] - 1
        vector_x_new[index] = vector_x[index] - theta * vector_z[i]
    vector_x_new[j0-1] = theta
    return vector_x_new


def simplex_method(A, vector_b, vector_c, vector_x, Jb, m, n):
    Ab = basis_matrix(A, Jb, m)   
    B = None
    if (B is None):
        B = np.linalg.inv(Ab)
    while True:
        vector_cb = np.array([vector_c[j-1] for j in Jb])
        print(vector_cb)
        
        vector_u = vector_cb.dot(B)
        print(vector_u)
        vector_delta = np.matmul(vector_u, A) - vector_c
        
        print(vector_delta)
        if(all([i >= 0 for i in vector_delta])):
            print('Bounded')
            print(vector_x)
            return
        
        #нашли минимальный элемент
        min_num = min(vector_delta)
        # найти индекс его J0
        for item in range(len(vector_delta)):
            if vector_delta[item] == min_num:
                J0 = item
        print(J0)
        print(min_num)
        
    
        #
        vector_z = np.matmul(B, A[: , J0])
        print(vector_z)
        
        
        #
        list_tetes = np.zeros(len(vector_z))    
        for item in range(len(vector_z)):
            if vector_z[item] > 0:
                list_tetes[item] = vector_x[Jb[item] - 1] / vector_z[item]
            else:
                list_tetes[item] = math.inf

        print(list_tetes)
        
        #
        min_teta_num = min(list_tetes)
        if min_teta_num == math.inf:
            print("Unbounded")
            return
        print(min_teta_num)
        
        # 
        for item in range(len(list_tetes)):
            if list_tetes[item] == min_teta_num:
                min_J = item
        
        print(min_J)
        
        Jb[min_J] = J0 + 1
        print(Jb[min_J])
        
        
        print("-----")
        # новый вектор
        new_vector_x = np.zeros(len(vector_x))
        print(new_vector_x)
        
        
        for i in range(m):
            index = Jb[i] - 1
            new_vector_x[index] = vector_x[index] - min_teta_num * vector_z[i]
        new_vector_x[J0] = min_teta_num        
        vector_x = new_vector_x.copy()
        
        
        B = calculations(B, Ab, A[: , J0], min_J + 1, m)
        
        
        if B is None:
            print("Unbounded")
            return
        

In [111]:
m, n = 4, 6
A = np.array([[1, 2, 1, 0, 0, 0],
            [2, 1, 0, 1, 0, 0],
            [1, 0, 0, 0, 1, 0],
            [0, 1, 0, 0, 0, 1]])
vector_b = np.array([10, 11, 5, 4])
vector_c = np.array([20, 26, 0, 0, 0, 1])
vector_x = np.array([2, 4, 0, 3, 3, 0])
Jb = np.array([5, 2, 1, 4])

In [112]:
simplex_method(A, vector_b, vector_c, vector_x, Jb, m, n)

[ 0 26 20  0]
[ 20.   0.   0. -14.]
[  0.   0.  20.   0.   0. -15.]
5
-15.0
[ 2.  1. -2.  3.]
[1.5 4.  inf 1. ]
1.0
3
6
-----
[0. 0. 0. 0. 0. 0.]
[ 0 26 20  1]
[10.  5.  0.  1.]
[0.00000000e+00 3.55271368e-15 1.00000000e+01 5.00000000e+00
 0.00000000e+00 1.33226763e-15]
Bounded
[4. 3. 0. 0. 1. 1.]


In [ ]:
#test 1
'''
m, n = 2, 2
A = np.array([[1, -1], 
             [2, 1]])
vector_b = np.array([3, 3])
vector_c = np.array([1, 1])
vector_x = np.array([1, 1])
Jb = np.array([2, 1])
'''
#test 2
'''m, n = 1, 2
A = np.array([[1, -1]]) # [2, 1]])
vector_b = np.array([0])
vector_c = np.array([1,2])
vector_x = np.array([0, 0])
Jb = np.array([1])
'''

#test 3
'''m, n = 4, 6
A = np.array([[1, 2, 1, 0, 0, 0],
            [2, 1, 0, 1, 0, 0],
            [1, 0, 0, 0, 1, 0],
            [0, 1, 0, 0, 0, 1]])
vector_b = np.array([10, 11, 5, 4])
vector_c = np.array([20, 26, 0, 0, 0, 1])
vector_x = np.array([2, 4, 0, 3, 3, 0])
Jb = np.array([5, 2, 1, 4])
'''